spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security-impl-v1
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    platform: postgres
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    liquibase: error
    com.suom: debug
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: debug

securityimplv1:
  app:
    jwtSecret: securityimplv1SecretKey
    jwtExpirationMs: 86400000
